
language: c

compiler:
  - clang
  - gcc

env:
  - LUA_VERSION=5.2.1
  - LUA_VERSION=5.2.0
  - LUA_VERSION=5.1.5

# Install cmake
install:
  - sudo apt-get update >/dev/null
  - sudo apt-get -q install cmake valgrind

# Run the Build script
script:
  - mkdir _build
  - cd _build
  - cmake .. -DCMAKE_INSTALL_PREFIX=../_install
  - cmake --build . --target install

